### ISSUE TITLE
How optional is drive_access_points_ft.txt ?

### ISSUE THREAD

**Issue by bhargavasana** [osplanning-data-standards/GTFS-PLUS#12]
Is drive_access_points_ft.txt mandatory is drive_access_ft.txt has been provided an input? If yes, it would be nice to mention that in the spec. 

Also, FT appears to be looking for columns drop_off and capacity in drive_access_points_ft.txt (for separating out PNR and KNR and for retaining only lots with capacity>0). Should these two fields be added to the list of mandatory fields in the file spec?

**Comment by e-lo** [comment]
I believe that this is the case - @lmz can you confirm?
