### ISSUE TITLE
Relation between lot_id and stop_id

### ISSUE THREAD

**Issue by bhargavasana** [osplanning-data-standards/GTFS-PLUS#14]
What is lot_id in drive_access_ft.txt and drive_access_points_ft.txt? FT code assumes that it will be different from stop_id. However, in the description of lot_id there is "stop_id". Do we want to make it clear that there should be no overlap between lot_id and stop_id? FT assigns numeric ids to both stops and lots for internal use.

**Comment by sdrewc** [comment]
@bhargavasana currently fasttrips requires lot_id != stop_id, correct?  In CHAMP sometimes they are equal, so in these cases we may need to create dummy lot_ids, something like "12345_lot"

**Comment by e-lo** [comment]
@sdrewc - where does lot_id == stop_id in champ?  that shouldn't be the
case and if it is should maybe be fixed?

**Comment by bhargavasana** [comment]
I got a bit more confused when I was testing FT today. After parking lot info is read in from drive_access_ft.txt, there is an attempt to merge with transfers data. The assumption probably is that from_stop_id/to_stop_id columns in transfers data match up with lot_id in drive_access data.

**Comment by bhargavasana** [comment]
@sdrewc - yes, lot_id must not be the same as stop_id in FT.

If we all agree, let us add a suffix/prefix to raw CHAMP lot_ids to make sure they are different from any of the stop_ids. Dependent input files (such as transfers_ft.txt) would need to be updated with new lot_ids in from_stop_id and to_stop_id fields.

**Comment by sdrewc** [comment]
@e-lo this happens in lots of places, in fact more than half of the pnrs in bus.pnr (anywhere there's a node instead of a nodepair).  It appears to have been done intentionally, and fixing it in champ would likely include recoding many bus lines in addition to the pnrs themselves.

**Comment by e-lo** [comment]
@sdrewc ahh, I remember now that this is how it is done for buses. I think @bhargavasana has a good fix for CHAMP --> GTFS-PLUS conversion script and I will make a queued clarification to the spec that clarifies that they cannot be the same.
