### ISSUE TITLE
stops_ft and stop_times_ft

### ISSUE THREAD

**Issue by sdrewc** [osplanning-data-standards/GTFS-PLUS#17]
Should stops_ft and stop_times_ft be required in GTFS-Plus? Per current specs only key fields are required and all attributes are optional:

https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/stops_ft.md
https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/stop_times_ft.md

**Comment by e-lo** [comment]
@sdrewc : per the [README.md](https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/README.md) , `stops_ft` and `stop_times_ft` are both required files.

Within these files, there are only a few fields that are _required_ for the file to work [ mainly the times themselves ]; is there another attribute that you think should be required?

**Comment by bhargavasana** [comment]
It appears like all fields in `stops_ft` and `stop_times_ft` are optional (most of the these variables are not present in model networks conventionally). The key fields provide no new information (and are present in the original GTFS files). The files therefore can safely be made optional under the current standard.

**Comment by e-lo** [comment]
AH, I understand now.  Yes, I believe this is the case.  @lmz or @stefancoe do you have any objections to this?
