### ISSUE TITLE
add _ft to filenames that are not GTFS files.

### ISSUE THREAD

**Issue by dantischler** [osplanning-data-standards/GTFS-PLUS#2]
Do we want to make all non-regular GTFS files include "_ft" in the filename? Several of the files that only exist in GTFS-PLUS do not currently have "_ft" in their filenames.

**Comment by e-lo** [comment]
@dantischler could you explain your reasoning? Is this just for consistency or is there a technical reason?

**Comment by dantischler** [comment]
No technical reason. This is just for consistency. Not necessary, but might help improve clarity regarding which files are part of GTFS and which are FT add-ons.

**Comment by lmz** [comment]
I like this too since when I was reading files and looking for doc I didn't know (until some time passed and I started to memorize the gtfs file names) which docs to look at.  So I think a more consistent convention is more convenient for stuff like this.

**Comment by e-lo** [comment]
...I just wish GTFS had an extension other than .txt that identified it. LeSigh.  WHY didn't they use .gtf ??
In any case, this is an easy fix:

 I will implement in GitHub spec.
@stefancoe can implement in 
@lmz please update the [Fast-Trips](https://github.com/MetropolitanTransportationCommission/fast-trips) code and test network
