### ISSUE TITLE
elevation_gain in walk_access_ft but what about egress?

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#20]
It strikes me that we reverse this for the egress but we don't know the elevation gain for the egress.  Is the gain supposed to be net gain or total gain (e.g. do downhill bits count against it?)

My recollection for CHAMP was that it's total gain (downhill bits have no effect) and so both access and egress elevation gain may be positive and we need to know both for this to be useful.

**Comment by e-lo** [comment]
For the specification as written we have two separate links for each stop/zone pair: one for access and one for egress...so this should be moot.

**Comment by lmz** [comment]
We do?  Wait where?  If they're only specified as taz/stop_id and not origin, destination, I don't see how this is true?

https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/walk_access_ft.md

**Comment by lmz** [comment]
drive access has "direction" but not walk access

**Comment by e-lo** [comment]
Gah - you are right!  I must have had drive access open. So two options for fixing then:
1.  Make walk access similar to drive access and have duplicate links (could also be handy since you might want to walk different way to/from...  
2. Just add a field for `elevation_loss`

**Comment by sdrewc** [comment]
I like option 1 even though it means bigger file sizes because it's consistent with how we do drive egress, and I think 'elevation_loss' is easier to misinterpret from a user perspective

**Comment by e-lo** [comment]
Let's do it.  Makes it consistent with drive.
