### ISSUE TITLE
Rename `fare_class` to `fare_period`

### ISSUE THREAD

**Issue by e-lo** [osplanning-data-standards/GTFS-PLUS#23]
@stefancoe : @lmz is [proposing renaming](https://github.com/osplanning-data-standards/GTFS-PLUS/issues/22) `fare_class` to `fare_period_id`.  Let's discuss [ here ].  

> As an aside, I find fare_class a little confusing since it's really a time bounded fare_id, right? So I like fare_period_id or something like that better, personally.

I don't see any issue with it other than that `fare_period_id` is super long.  Maybe `fare_period` ?

**Comment by lmz** [comment]
`fare_period` makes sense, the `_id` part isn't really useful.

**Comment by stefancoe** [comment]
Fine by me.

**Comment by stefancoe** [comment]
I tried to make the changes but could not commit because of permissions.

**Comment by lmz** [comment]
What about senior or youth fares, or low-income fares?  Fare_class definitions might make sense for user-based fares definitions.

**Comment by e-lo** [comment]
Agree
