### ISSUE TITLE
Fare rules assumptions

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#28]
In implementing fare rules matching in fast-trips, I had to make certain assumptions which I documented here: https://github.com/MetropolitanTransportationCommission/fast-trips/tree/fares#fares

Do these make sense to folks?

**Comment by sdrewc** [comment]
Looks good! FWIW only cases 1 (fare_id + origin_id + destination_id) and 2 (fare_id) _should_ be present in the San Francisco network at present.

**Comment by e-lo** [comment]
> These combinations of route_id, origin_id, and destination_id will be used to match a fare_id to a transit trip, in this order. The first match will win.
> Matching route_id, origin_id and destination_id
> Matching route_id only (no origin_id or destination_id specified)
> Matching origin_id and destination_id only (no route_id specified)
> No match (e.g. fare_id specified with no other columns)
