### ISSUE TITLE
Consolidate pnr.txt and knr.txt

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#3]
https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/pnr.md
https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/knr.md

I would think that most knrs would be a subset of pnrs so we could consolidate these files for simplicity.  We could add a mandatory field, like 'type', with values like 'knr', 'pnr' or 'both'.

**Comment by e-lo** [comment]
Questions for @lmz, @stefancoe + @sdrewc ...
- is it actually helpful / necessary in some cases to have separate nodes for KNR and PNR (i.e. many BART stations where they enter from different points on the network..and do we need to cut off capacity/access to one (PNR) before the other (KNR) in the event that it gets overfull?
- not all KNRs have PNRs (i.e. Balboa Park) but they do often have hide and rides...
- would it make sense to have a generic "lot" that could also in the future be used for parking lots or is that over-planning?

**Comment by lmz** [comment]
My thoughts:
- I think that when the KNR and PNR for a station enters from different points on the network (they're physically separated), then you'd want to give them separate lot ids and then they could still have separate entries.  If we go this way, the docs should elaborate on this.
- I'm confused about the capacity part -- doesn't capacity only apply to a PNR?
- Likewise, I would think that a hide and ride wouldn't be the same lot id as the KNR.  I would think they'd only have the same lot id if they connect to the network the same way... I would guess that a hide and ride would typically have a longer travel_time between the TAZ and "lot".

**Comment by e-lo** [comment]
From discussing with @lmz and Bhargava:
- one file, called `drive_access_point_ft.txt` that has KNR, Taxi, HNR and PNR
- separate points for each one that you would access separately from the hwy network
- add a field for KNR, HNR, PNR indication
