### ISSUE TITLE
Update fare_transfer_rules columns

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#31]
In fare_transfer_rules_ft.txt, 'transfer_rule' isn't very descriptive especially for a number value.
Isn't this column the discount?  So it would be $.25 or $.50 or 50% or 100%?  I think 'discount' would be more clear as a column name?

**Comment by e-lo** [comment]
There are three basic properties that can happen in addition to the base condition that assumes that a full new fare is paid with each boarding.
1. Fare reduction of XX cents off the sum total of both fares
2. Transfer cost of XX cents 
3. Free transfers, or a 100% discount

It seems like we should have one column that specifies the type of xfer and the other the value?

Given that in some places, transfers have a cost, perhaps "discount" is not necessarily the right word either.

Here is my straw man:

**`type`** : One of: free, cost, or discount 
**`amount`** : A number  

Thoughts?

**Comment by lmz** [comment]
Sounds good to me!
Do we need to distinguish between a flat discount (e.g. $.50) or a percentage discount (e.g. 50%)?

so maybe:
`type`: one of `discount_percent`, `discount_flat`, or `transfer_fare`
`amount`: number

**Comment by ddorinson** [comment]
@lmz - Do we also need to add `free` to your proposed choice set for `type` ? Or, would a user choose `transfer_fare` with `amount` = $0.00?

**Comment by lmz** [comment]
I don't think it's necessary since it's covered as you said (or with 
`type`=`discount_percent` and `amount`=1.0)

**Comment by e-lo** [comment]
I was going to suggest these three [ `discount_flat`, `discount_percent`, and `transfer_fare` ] but couldn't think of an instance where the `discount_percent` wouldn't be 100% [ aka free ] so just made it explicit.  I'd be fine either way.

**Comment by lmz** [comment]
Hmm... I would think 50% discounts would come in sometimes?  Like this: https://www.amtrak.com/children-discounts

But wait, that's age-based!  Gah!  We don't have a way to do that...  And actually I'd think the senior discount is important to folks... https://www.sfmta.com/news/notices/fares-fees-and-fines-effective-july-1-2015

**Comment by e-lo** [comment]
Good point. But that would occur in xfers, that is a fare class...right?

**Comment by lmz** [comment]
Yes, it's more of a fare_period definition so more relevant to the issue on fare periods (issue#23) ... so maybe that's why fare_period might be called fare_class?

Fair enough (har), I couldn't find percentage fare discounts so maybe free is sufficient.  :dancer:

**Comment by lmz** [comment]
I think it might be an option to output these columns in the pathset links file, so I'm thinking it would be more clear if we called the columns `transfer_type` and `transfer_amount` so they could keep their names in the output and still be clear.

**Comment by e-lo** [comment]
I'd be cool with that.  @stefancoe and @sdrewc  - can you weigh in before we adopt?

Proposal:

`transfer_type`: One of: `free_transfer`, `transfer_cost`, or `transfer_discount`  
     `transfer_cost` assumes that the full value fare is not paid again  
     `transfer_discount` is a subtraction from the cumulative fare  
`transfer_cost`: value in whatever the fare currency is that is added or subtracted

**Comment by lmz** [comment]
I admit there's some part of my brain that really wants it to be `transfer_cost`, `transfer_discount` and `transfer_free` (instead of `free_transfer`)...  :open_mouth:

**Comment by sdrewc** [comment]
I may be missing something... is there a reason we couldn't just have one field, `transfer_cost`, with whatever the incremental cost of the transfer is?

**Comment by lmz** [comment]
I think it's for maintainability.  Transfers are often described as discounts (for example, here: http://www.caltrain.com/Fares/faresmisc/Inter-agency_Transfers.html)

It makes sense to code them that way rather than replicating all the fares and subtracting the discount, and when fares change but transfer discounts don't, it's more intuitive to update the fares and not to update the transfer fares (since they're just discounts).

**Comment by sdrewc** [comment]
Ahh makes sense.  Then I'm fine with @e-lo 's proposal (and @lmz 's `transfer_free`)

**Comment by lmz** [comment]
oh shoot, `transfer_type` is already a field in transfers.txt (https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/transfers.md).

`transfer_fare_type` and `transfer_fare_amount` then?  I know it's getting longer but that's ok...

**Comment by e-lo** [comment]
Re `transfer_free`: you are ridiculous, @lmz but fine 👍  
Re `transfer_fare_type`: I think this is fine...good catch!

So....

**Revised Proposal:**

`transfer_fare_type`: One of: `transfer_free`, `transfer_cost`, or `transfer_discount`  
- `transfer_cost` assumes that the full value fare is not paid again  
-  `transfer_discount` is a subtraction from the cumulative fare  
- `transfer_cost`: value in whatever the fare currency is that is added or subtracted

Going once...going twice...

**Comment by stefancoe** [comment]
Sounds good to me!

**Comment by ddorinson** [comment]
I like this, but before you copy-paste... I think the third bullet should actually be top-level, defining the second of the two fields (instead of further commentary on `transfer_fare_type`), right?

**Comment by e-lo** [comment]
Good catch, @ddorinson .  I also added a slight bit of clarity about transfer_free and what the second value actually means (it should be non-negative!)

And....what about `transfer_fare` instead of `transfer_cost` since this column applies to both cost or discount??

"Final Final" Change:

`transfer_fare_type`: One of: `transfer_free`, `transfer_cost`, or `transfer_discount`
- `transfer_cost` assumes that the full value fare is not paid again
- `transfer_discount` is a subtraction from the cumulative fare
- `transfer_free` is a ridiculous way to say "free transfer"

`transfer_fare`: _non-negative_ value in whatever the fare currency that is added to the initial fare in the case of a transfer cost or subtracted from the combined fare of the segments in the case of transfer discount.

**Comment by lmz** [comment]
"ridiculous"?!  :laughing:

**Comment by stefancoe** [comment]
Given that transfer_cost: assumes that the full value fare is not paid again, what indicates that the full fare is paid again? Is it if the tranfer_fare_type is empty/null? Or is that not an option and the amount of the full fare would be entered in the transfer_fare column?
