### ISSUE TITLE
`walk_access_ft` should have have direction field like `drive_access_ft`

### ISSUE THREAD

**Issue by sdrewc** [osplanning-data-standards/GTFS-PLUS#35]
I think `walk_access_ft` should have a direction field that can have values 'access' or 'egress' similar to the way implemented in `drive_access_ft` because they use [taz, stop_id] rather than [from_node, to_node].  Do you guys agree?

**Comment by e-lo** [comment]
Yes - this was an oversight. let me address ASAP.
