### ISSUE TITLE
TAZ locations for access/egress visualization

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#4]
I really like being able to visualize the network when I'm tracing through things, but since we just have the gtfs viewer right now, I have a limited visual.  In the long term, if we were to make a fasttrips visualization tool, we'd probably want to be able to see access/eggress links and so we'd need TAZ locations (or centroid locations) so maybe that should be in an optional file.

**Comment by e-lo** [comment]
@stefancoe and @lmz 
What do you think about the following specification, which is similar to [`stops.txt`](https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/stops.md)
`zones_ft.txt`

| _Field Name_ | _Description_ |
| --- | --- |
| `zone_id` | Required. Str or other type. |
| `zone_name` | Optional. String. |
| `zone_lat` | Required. Float. |
| `zone_long` | Required. Float. |
