### ISSUE TITLE
Dwell formula, acceleration, deceleration specification in vehicles_ft.txt

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#40]
In the test network, this is specified:
https://github.com/MetropolitanTransportationCommission/fast-trips/blob/develop/Examples/test_network/input/vehicles_ft.txt

**Comment by e-lo** [comment]
To add a little more detail:

- Lisa has been updating the test network as she has been updating Fast-Trips . 
- Now Fast-Trips requires things about acceleration, decelleration and dwell time in `vehicles_ft.txt`   
- The v0.3 spec for GTFS+ doesn't require these . 
- We need a v0.31 that has these features required .

**Comment by AngelaQYang** [comment]
Where is v0.31?

**Comment by sdrewc** [comment]
Working on updates for v0.3.1 now, although will be somewhat different than this issue specifies.  Soon, vehicles_ft will include TCQSM parameters, and Fast-Trips will perform TCQSM calcs based on those.

@e-lo  and @lmz I don't recall: did we decide accel and decel would be in GTFS-Plus or in some other config file?

**Comment by e-lo** [comment]
Fixed in v0.4
Commit: https://github.com/osplanning-data-standards/GTFS-PLUS/commit/3ef7a003e60ea463c75ae406b414c11675e6783a
