### ISSUE TITLE
Route type/mode dwell interaction coeffs

### ISSUE THREAD

**Issue by sdrewc** [osplanning-data-standards/GTFS-PLUS#43]
We don't currently have a place to put dwell time coefficients related to route type.  In the estimation, we ended up with owl, rapid, and express, each interacting with base dwell time, and boards/alights.  Now we're putting a formula into `dwell_formula` in `vehicles_ft.txt`, but that doesn't make sense for route-type variables.  I wonder if we need a new file `dwell_ft.txt` with `vehicle_name`, `mode`, `constant`, `per_board`, `per_alight`, `friction`.  Other thoughts about this, @e-lo, @lmz, @bhargavasana, @stefancoe?

**Comment by e-lo** [comment]
@sdrewc  -  there were a few variables that we used in estimation that we didn't foresee using in forecasting for various reasons.  I think it is fine to leave them out of the prediction.

**Comment by sdrewc** [comment]
sounds good.
