### ISSUE TITLE
max_speed occurs twice in vehicles_ft.md

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#44]
max_speed is in here twice :dancing_women:

**Comment by lmz** [comment]
Also, the vehicles_ft.md says, for seated_capacity, "If specified, this will override capacity from trip file."  As far as I can tell, there's no capacity or seated_capacity in the trip file.  Clarify or remove?

**Comment by e-lo** [comment]
Fixed here: https://github.com/osplanning-data-standards/GTFS-PLUS/commit/4b21e39effcdb991cf2bd72a0f1ee4eba296d282
