### ISSUE TITLE
bike access/egress?

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#5]
I was noticing that we reference some bike attributes here and in the demand specification but we have no specification for how bike access and egress links could be specified, just walk and drive.  Are we leaving this intentionally as a TODO?  I think one could argue that we might as well specify it up front?

**Comment by e-lo** [comment]
@lmz , this is an easy fix so we might as well add it.  I modeled it after walk access and added some bike specific things.
