### ISSUE TITLE
Costs

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#6]
The fares have a currency_type and price https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/fare_attributes.md

While the drive access links have a cost field specified as 'Integer in cents'.  I would think we'd want to be consistent?

And also, now that I think about it, maybe the currency should be specified in one place, or do we really want to let things be configured in multiple currencies?

**Comment by e-lo** [comment]
This was something I noticed as well.  I agree that:
- We want to currency to only be specified in one place, and
- It should probably be consistent across the specification.

I'll make the change in drive access links.

**Comment by ddorinson** [comment]
Found this old issue when trying to research the history of `drive_access_points_ft.txt`... Am I correct that all monetary costs in FT are now expressed as floats?  The T2 memo has some stray references to an integer number of cents, which I *think* is long gone, but the descriptions in [`drive_access_points_ft.txt`](https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/drive_access_points_ft.md) do not specify a data type, so I'm not 100% sure.  Can @lmz or @elo confirm?

**Comment by e-lo** [comment]
I think those stray references are...'astray'.
Floats it is!

**Comment by ddorinson** [comment]
Excellent.  Thank you!
