### ISSUE TITLE
transfers spec mentions PNR/KNR

### ISSUE THREAD

**Issue by lmz** [osplanning-data-standards/GTFS-PLUS#7]
https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/transfers.md

Currently says 
"File MUST contain a record for each Park and Ride:transit stop pair that can be accessed on foot.
File MUST contain a record for each Kiss and Ride:transit stop pair that can be accessed on foot."

I think this is an error (maybe should say MUST NOT?) because gtfs readers complain about not knowing anything about PNR/KNR nodes.  We could note that PNR:transit stop and KNR:transit stop relationships belong in the transfers_ft.md file only

**Comment by e-lo** [comment]
I think the intent was for the "funnel links" to be represented here?

**Comment by lmz** [comment]
My understanding is that the funnel links need to be in `transfers_ft.txt` and not in `transfers.txt`.  A little confusing and not ideal, but gtfs validators will complain about transfers that are not just stop-to-stop.  

This is the way fast-trips currently operates:
See test_network **`transfers.txt`**: https://github.com/MetropolitanTransportationCommission/fast-trips/blob/master/Examples/test_network/input/transfers.txt
and test_network **`transfers_ft.txt`**: https://github.com/MetropolitanTransportationCommission/fast-trips/blob/master/Examples/test_network/input/transfers_ft.txt

**Comment by e-lo** [comment]
transfers.txt is ONLY stop to stop
transfers_ft.txt is lot to stop AND stop to stop
